---
- hosts: esdlpoc01.csmc.edu
  tasks:
    - name: copy a file
      file: 
        path: /home/julianoo/tmp/testfile
        state: touch
      register: output
    - debug: msg="Register output is {{output}}" 
    - name: edit file
      lineinfile:
        path: /home/julianoo/tmp/testfile
        line: "{{output}}"
